stages:
  - test

sudo: required
cache: bundler
language: ruby

services:
  - docker

install:
  - bundle install

env:
  matrix:
    - INSTANCE: debian-9
    - INSTANCE: ubuntu-1804
    - INSTANCE: ubuntu-1604
    - INSTANCE: centos-7
    - INSTANCE: fedora
    - INSTANCE: opensuse-42

script: 
  - bundle exec kitchen verify ${INSTANCE}
